name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
            webhook: ${{ secrets.DISCORD_WEBHOOK }}
            status: ${{ job.status }}
            title: "deploy"
            description: "Build and deploy to GitHub Pages"
            nofail: false
            nocontext: false
            noprefix: false
            color: 0x0000ff
            username: GitHub Actions
            avatar_url: ${{ secrets.AVATAR_URL }}
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with Pylint
      run: |
        pip install pylint
        pylint

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        title: "deploy"
        description: "Build and deploy to GitHub Pages"
        nofail: false
        nocontext: false
        noprefix: false
        color: 0x0000ff
        username: GitHub Actions
        avatar_url: ${{ secrets.AVATAR_URL }}
